# Generated by Django 4.1 on 2022-09-09 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=30)),
                ('usernames', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GroupMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.group')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='messages',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.groupmessages'),
        ),
    ]
