# Generated by Django 4.1 on 2022-09-10 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='messages',
        ),
        migrations.RemoveField(
            model_name='groupmessages',
            name='group_id',
        ),
    ]
