# Generated by Django 4.1 on 2022-09-11 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_group_messages_groupmessages_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='messages',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.groupmessages'),
        ),
        migrations.AlterField(
            model_name='groupmessages',
            name='group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.group'),
        ),
    ]
